# Generated by Django 5.2.10 on 2026-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('liturgical_time', models.CharField(max_length=40)),
                ('sunday_number', models.PositiveIntegerField()),
                ('central_message', models.CharField(max_length=200)),
                ('free_content', models.TextField()),
                ('premium_content', models.TextField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Domingo',
                'verbose_name_plural': 'Domingos',
                'ordering': ['liturgical_time', 'sunday_number'],
            },
        ),
    ]
